conda env remove d2l-zh
conda create -n -y d2l-zh python=3.8 pip
conda activate d2l-zh

pip install -y jupyter d2l torch torchvision

wget https://zh-v2.d2l.ai/d2l-zh.zip
unzip d2l-zh.zip
jupyter notebook

In [49]:
##########  访问数组里的元素
#   一个，行列，集中、分散子区域
import numpy as np
a = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16]
])
print(a[-1])
print(a[1,2],a[1,:],a[:,1],a[1:3,1:],a[::3,::2],sep="\n")



[13 14 15 16]
7
[5 6 7 8]
[ 2  6 10 14]
[[ 6  7  8]
 [10 11 12]]
[[ 1  3]
 [13 15]]


In [ ]:
##########  创建张量
#   arange(s), zeros((x,y,h)), ones((x,y,h)), tensor([ [2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1] ]), 逻辑运算符, sum()
print("创建张量")
import torch
x1= torch.arange(12)
x2= torch.zeros((2,3,4))
x3= torch.ones((2,3,4))
x4= torch.tensor([ [2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1] ])
X= x2==x3
print(x1.sum(),x2.sum(), x3.sum())
print(x1, x2, x3, x4, X, sep="\n")


##########  张量运算【加减乘除】
print("张量运算")
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x1 = x + y
x2 = x - y
x3 = x * y
x4 = x / y
print(x, y, x1, x2, x3, x4, sep="\n")

##########  张量连结
print("张量连结")
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
x5 = torch.cat((X, Y),dim=0)
x6 = torch.cat((X, Y),dim=1)
print(X, Y, x5, x6, sep="\n")



创建张量
tensor(66) tensor(0.) tensor(24.)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]])
张量运算
tensor([1., 2., 4., 8.])
tensor([2, 2, 2, 2])
tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
张量连结
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,

In [47]:
##########  张量广播机制
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
c = a+b
print(a, b, c, sep="\n")

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [ ]:
##########  访问张量的形状和元素总数,改变张量形状
#   shape,numel()，reshape(x,y,...)、reshape((1,-1))、reshape((-1,1))
x1 = torch.arange(12)
print(x1,x1.shape,x1.numel(),sep="\n")
x2 = x1.reshape(3,4)
x3 = x1.reshape((-1,1))
x4 = x1.reshape((1,-1))
x2, x3, x4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]))

In [61]:
##########  写入张量
print("写入张量")
X = torch.arange(12).reshape((3,4))
print(X)
print(X[1,2])
X[1,2] = 9
print(X[1,2])

print(X)
print(X[1:2,:])
X[1:2,:] = 12
print(X[1:2,:])

##########  转化为numpy张量，大小为 1 的张量转 Python 标量
print("转化为numpy张量")
A = X.numpy()
# 将 NumPy 数组 A 转换回 PyTorch 张量
B = torch.tensor(A)
# 查看两者的数据类型
print(type(A), type(B), sep="\n")

print("大小为 1 的张量转 Python 标量")
# 创建一个仅包含单个元素的张量
a = torch.tensor([3.5])
# 多种方式提取为 Python 标量
print(a, a.item(), float(a), int(a), sep="\n")


写入张量
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(6)
tensor(9)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])
tensor([[4, 5, 9, 7]])
tensor([[12, 12, 12, 12]])
转化为numpy张量
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
大小为 1 的张量转 Python 标量
tensor([3.5000])
3.5
3.5
3


### 第一段：验证运算后张量地址变化
```python
# 记录 Y 原来的内存地址
before = id(Y)
# 执行加法运算并重新赋值
Y = Y + X
# 比较运算前后 Y 的内存地址是否相同
id(Y) == before
```

---

### 第二段：执行原地操作（保持内存地址不变）
```python
# 创建一个和 Y 形状、数据类型相同的全零张量 z
z = torch.zeros_like(Y)
# 打印 z 初始的内存地址
print('id(z):', id(z))

# 使用切片语法, 执行原地赋值，不会创建新张量
z[:] = X + Y
# 再次打印 z 的内存地址，验证地址未变
print('id(z):', id(z))


#  X += Y 也是原地操作
before = id(X)
X += Y
id(X) == before
```


In [ ]:
########### 数据预处理
#   建立文件夹（ os.makedirs(,) ）、文件（ os.path.join(,,) ）
import os
os.makedirs(os.path.join("..","data"),exist_ok=True)
data_file = os.path.join("..","data","house_tiny.cvs")
with open(data_file,"w") as f:
    f.write("NumRooms,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

#   数据加载、读取（ read_csv() ）
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [ ]:
##########  处理数据-【缺失数据】
#   插值法（ .fillna( . ) ）
inputs, outputs = data.iloc[:, 0:2], data.iloc[:,2]
inputs = inputs.fillna( inputs.mean(numeric_only=True) )
print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True)
inputs = inputs.replace( {True:1, False:0} )
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


C:\Users\YZC\AppData\Local\Temp\ipykernel_30060\2937052726.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  inputs = inputs.replace({True:1, False:0})


In [23]:
#   inputs和outputs中所有条目都是数值类型，就可转化为张量格式
#   数值型dataframe转化为张量
import torch
x,y = torch.tensor(inputs.values), torch.tensor(outputs.values)
print(x,y,sep="\n")

# 将大小为1的张量转换为Python标量
a = torch.tensor([3.5]) # 创建一个大小为1的张量
result = (a, a.item(), float(a), int(a)) # 多种方式将其转为Python标量
print(result)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500, 106000, 178100, 140000])
(tensor([3.5000]), 3.5, 3.5, 3)
